services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./packages/server/public:/var/www/graphCalculator/public
      - ./packages/client/dist:/var/www/graphCalculator/dist
